In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [25]:
df = pd.read_csv('./data/nbaFeaturedEngineered.csv')
df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,visitor_DRtg,home_DRtg,visitor_turn_over_ratio,home_turn_over_ratio,visitor_efg%,home_efg%,visitor_ts%,home_ts%,home_win,total_points
0,142.0,53.0,105.0,0.505,26.0,37.0,0.703,10.0,25.0,0.400,...,123.046225,119.167506,8.419533,6.741848,0.552381,0.547170,0.585422,0.600844,1,290.0
1,114.0,41.0,76.0,0.539,18.0,24.0,0.750,14.0,30.0,0.467,...,99.420050,112.871287,12.845215,12.030075,0.631579,0.482558,0.658503,0.494845,0,210.0
2,98.0,36.0,93.0,0.387,15.0,19.0,0.789,11.0,33.0,0.333,...,102.554180,100.122599,12.026033,12.511730,0.446237,0.539474,0.483425,0.603095,1,204.0
3,116.0,46.0,89.0,0.517,9.0,14.0,0.643,15.0,34.0,0.441,...,120.008496,117.029863,5.461923,8.585701,0.601124,0.539326,0.609500,0.570016,0,229.0
4,123.0,43.0,77.0,0.558,27.0,34.0,0.794,10.0,24.0,0.417,...,107.885445,114.996260,15.332944,11.682243,0.623377,0.477273,0.668769,0.534188,0,233.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9505,119.0,44.0,83.0,0.530,17.0,21.0,0.810,14.0,34.0,0.412,...,107.741421,124.372910,9.336398,8.752387,0.614458,0.556250,0.645056,0.602141,0,227.0
9506,130.0,52.0,88.0,0.591,10.0,13.0,0.769,16.0,32.0,0.500,...,116.832093,124.045802,7.816941,9.572901,0.681818,0.545977,0.693555,0.589770,0,243.0
9507,110.0,42.0,89.0,0.472,18.0,23.0,0.783,8.0,25.0,0.320,...,90.725806,114.535610,10.842627,16.523463,0.516854,0.606667,0.554883,0.603364,0,209.0
9508,139.0,53.0,94.0,0.564,21.0,21.0,1.000,12.0,30.0,0.400,...,106.913756,124.955052,8.112831,8.903587,0.627660,0.530000,0.673189,0.549249,0,259.0
9509,113.0,41.0,84.0,0.488,22.0,24.0,0.917,9.0,31.0,0.290,...,109.676097,111.704231,12.540572,14.268549,0.541667,0.565476,0.597504,0.593390,0,220.0

In [26]:
df.isnull().sum()

visitor_points             0
visitor_fgm                0
visitor_fga                0
visitor_fgp                0
visitor_ftm                0
visitor_fta                0
visitor_ftp                0
visitor_tpm                0
visitor_tpa                0
visitor_tpp                0
visitor_offReb             0
visitor_defReb             0
visitor_totReb             0
visitor_assists            0
visitor_pFouls             0
visitor_steals             0
visitor_turnovers          0
visitor_blocks             0
visitor_team               0
home_points                0
home_fgm                   0
home_fga                   0
home_fgp                   0
home_ftm                   0
home_fta                   0
home_ftp                   0
home_tpm                   0
home_tpa                   0
home_tpp                   0
home_offReb                0
home_defReb                0
home_totReb                0
home_assists               0
home_pFouls                0
home_steals                0
home_turnovers             0
home_blocks                0
home_team                  0
visitor_drb%               1
home_drb%                  1
visitor_orb%               1
home_orb%                  1
visitor_fta_rate           1
home_fta_rate              1
visitor_possessions        0
home_possessions           0
visitor_to%                1
home_to%                   1
visitor_ORtg               0
home_ORtg                  0
visitor_DRtg               0
home_DRtg                  0
visitor_turn_over_ratio    1
home_turn_over_ratio       1
visitor_efg%               1
home_efg%                  1
visitor_ts%                0
home_ts%                   0
home_win                   0
total_points               0
dtype: int64

In [27]:
df = df.dropna()

In [28]:
# Create first target column 'winner'
df['home_win'] = df.apply(
    lambda row: 1 if row['home_points'] > row['visitor_points'] else 0,
    axis=1
)
# Create second target column 'total_points'
df['total_points'] = df['home_points'] + df['visitor_points']

# Display
df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_14576\3911342885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['home_win'] = df.apply(
C:\Users\User\AppData\Local\Temp\ipykernel_14576\3911342885.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_points'] = df['home_points'] + df['visitor_points']

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,visitor_DRtg,home_DRtg,visitor_turn_over_ratio,home_turn_over_ratio,visitor_efg%,home_efg%,visitor_ts%,home_ts%,home_win,total_points
0,142.0,53.0,105.0,0.505,26.0,37.0,0.703,10.0,25.0,0.400,...,123.046225,119.167506,8.419533,6.741848,0.552381,0.547170,0.585422,0.600844,1,290.0
1,114.0,41.0,76.0,0.539,18.0,24.0,0.750,14.0,30.0,0.467,...,99.420050,112.871287,12.845215,12.030075,0.631579,0.482558,0.658503,0.494845,0,210.0
2,98.0,36.0,93.0,0.387,15.0,19.0,0.789,11.0,33.0,0.333,...,102.554180,100.122599,12.026033,12.511730,0.446237,0.539474,0.483425,0.603095,1,204.0
3,116.0,46.0,89.0,0.517,9.0,14.0,0.643,15.0,34.0,0.441,...,120.008496,117.029863,5.461923,8.585701,0.601124,0.539326,0.609500,0.570016,0,229.0
4,123.0,43.0,77.0,0.558,27.0,34.0,0.794,10.0,24.0,0.417,...,107.885445,114.996260,15.332944,11.682243,0.623377,0.477273,0.668769,0.534188,0,233.0

In [29]:
# Apply one-hot encoding and convert to booleans to integers
encoded_df = pd.get_dummies(df, columns=['visitor_team', 'home_team'])

# Display
new_df = encoded_df.replace({True: 1, False: 0})
new_df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_14576\525790992.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = encoded_df.replace({True: 1, False: 0})

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_team_Oklahoma City Thunder,home_team_Orlando Magic,home_team_Philadelphia 76ers,home_team_Phoenix Suns,home_team_Portland Trail Blazers,home_team_Sacramento Kings,home_team_San Antonio Spurs,home_team_Toronto Raptors,home_team_Utah Jazz,home_team_Washington Wizards
0,142.0,53.0,105.0,0.505,26.0,37.0,0.703,10.0,25.0,0.400,...,0,0,0,0,0,0,0,0,0,0
1,114.0,41.0,76.0,0.539,18.0,24.0,0.750,14.0,30.0,0.467,...,0,0,0,0,0,1,0,0,0,0
2,98.0,36.0,93.0,0.387,15.0,19.0,0.789,11.0,33.0,0.333,...,0,0,0,0,0,0,0,0,0,0
3,116.0,46.0,89.0,0.517,9.0,14.0,0.643,15.0,34.0,0.441,...,1,0,0,0,0,0,0,0,0,0
4,123.0,43.0,77.0,0.558,27.0,34.0,0.794,10.0,24.0,0.417,...,0,0,0,1,0,0,0,0,0,0

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# Split Data
X = new_df.drop(columns=['home_win', 'total_points'])
y_winner = df['home_win']
y_total = df['total_points']

X_train, X_test, y_winner_train, y_winner_test = train_test_split(X, y_winner, test_size=0.2, random_state=42)
_, _, y_total_train, y_total_test = train_test_split(X, y_total, test_size=0.2, random_state=42)

# Train Models
clf = RandomForestClassifier()
clf_model = clf.fit(X_train, y_winner_train)

reg = RandomForestRegressor()
reg_model = reg.fit(X_train, y_total_train)

# Predictions
winner_prediction = clf_model.predict(X_test)
total_predictions = reg_model.predict(X_test)

In [32]:
winner_prediction

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [33]:
total_predictions

array([238.1 , 186.68, 225.55, ..., 200.51, 251.77, 226.78])

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_winner_pred = clf_model.predict(X_test)
print(confusion_matrix(y_winner_test, y_winner_pred))
print(classification_report(y_winner_test, y_winner_pred))
print("Accuracy: ", accuracy_score(y_winner_test, y_winner_pred))

[[908  18]
 [  7 969]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       926
           1       0.98      0.99      0.99       976

    accuracy                           0.99      1902
   macro avg       0.99      0.99      0.99      1902
weighted avg       0.99      0.99      0.99      1902

Accuracy:  0.9868559411146162

In [35]:
from sklearn.metrics import mean_squared_error, r2_score

y_total_pred = reg_model.predict(X_test)
print("MSE: ", mean_squared_error(y_total_test, y_total_pred))
print("R2 Score: ", r2_score(y_total_test, y_total_pred))

MSE:  1.0107345951629871
R2 Score:  0.9978038080573306

In [ ]:
# Input Teams
visitor_team = input("Enter Away Team: ")
home_team = input("Enter Home Team: ")

# Prepare Input Data
input_data = {col: 0 for col in X.columns}  # Initialize all columns with 0

# Set team-specific features
if f'home_team_{home_team}' in input_data:
    input_data[f'home_team_{home_team}'] = 1
if f'visitor_team_{visitor_team}' in input_data:
    input_data[f'visitor_team_{visitor_team}'] = 1

# For numeric features, use the mean (or other default values)
for col in X.select_dtypes(include=['float64', 'int64']).columns:
    input_data[col] = X[col].mean()

# Convert to DataFrame
input_df = pd.DataFrame([input_data])

# Predict Winner
predicted_winner = clf_model.predict(input_df)[0]
winning_team = home_team if predicted_winner == 1 else visitor_team

# Predict Total Points
predicted_total_points = reg_model.predict(input_df)[0]

# Display Results
print("Predicted Winner:", winning_team)

Predicted Winner: Milwaukee Bucks
Predicted Total Points: 222.0