In [194]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [195]:
game_df = pd.read_csv('./data/gameStatistics.csv') # change path to ./data/gameStatistics contains the game_ids when cleaned properly
game_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,18.0,34.0,2.0,NaN,20.0,NaN,97.0,34.0,82.0,41.5,...,37.0,43.0,33.0,25.0,8.0,20.0,7.0,24.0,240:00,Atlanta Hawks
1,25.0,46.0,12.0,NaN,18.0,NaN,107.0,40.0,90.0,44.4,...,39.0,44.0,31.0,22.0,10.0,17.0,10.0,11.0,240:00,Atlanta Hawks
2,15.0,36.0,3.0,NaN,10.0,NaN,101.0,37.0,102.0,36.3,...,40.0,53.0,23.0,20.0,4.0,11.0,9.0,1.0,240:00,Atlanta Hawks
3,8.0,36.0,0.0,NaN,6.0,NaN,72.0,28.0,88.0,31.8,...,46.0,49.0,20.0,16.0,7.0,15.0,15.0,17.0,240:00,Atlanta Hawks
4,8.0,32.0,10.0,NaN,9.0,NaN,83.0,29.0,77.0,37.7,...,38.0,51.0,30.0,17.0,13.0,12.0,3.0,27.0,240:00,Atlanta Hawks

In [196]:
game_df.describe()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus
count,2319.000000,2319.000000,2319.000000,2009.000000,2319.000000,2009.000000,3057.000000,3057.000000,3057.000000,3057.000000,...,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000,3057.000000
mean,12.349720,44.878827,11.448038,12.816327,16.357050,10.516177,108.734053,40.016683,87.152764,45.974583,...,35.553876,10.363428,33.831534,44.194962,24.219496,20.004907,7.586523,13.751390,4.946680,0.564933
std,6.277979,9.807574,8.957032,5.490177,6.282615,2.758519,13.566358,5.537892,7.395070,5.581095,...,8.777542,3.798734,5.491791,6.561973,5.220834,4.290610,2.974002,3.999961,2.554274,14.548342
min,0.000000,14.000000,0.000000,0.000000,0.000000,4.000000,64.000000,21.000000,54.000000,27.100000,...,0.000000,1.000000,16.000000,26.000000,7.000000,8.000000,0.000000,3.000000,0.000000,-60.000000
25%,8.000000,38.000000,5.000000,9.000000,12.000000,9.000000,100.000000,36.000000,82.000000,42.200000,...,29.700000,8.000000,30.000000,40.000000,21.000000,17.000000,5.000000,11.000000,3.000000,-9.000000
50%,12.000000,44.000000,10.000000,12.000000,16.000000,10.000000,109.000000,40.000000,87.000000,45.900000,...,35.500000,10.000000,34.000000,44.000000,24.000000,20.000000,7.000000,14.000000,5.000000,1.000000
75%,16.000000,52.000000,17.000000,16.000000,20.000000,12.000000,118.000000,44.000000,92.000000,49.500000,...,41.400000,13.000000,37.000000,48.000000,28.000000,23.000000,9.000000,16.000000,6.000000,10.000000
max,53.000000,80.000000,67.000000,35.000000,42.000000,26.000000,158.000000,65.000000,128.000000,65.500000,...,68.400000,27.000000,56.000000,70.000000,43.000000,39.000000,22.000000,29.000000,20.000000,50.000000

In [197]:
game_df.dtypes

visitor_fastBreakPoints       float64
visitor_pointsInPaint         float64
visitor_biggestLead           float64
visitor_secondChancePoints    float64
visitor_pointsOffTurnovers    float64
visitor_longestRun            float64
visitor_points                float64
visitor_fgm                   float64
visitor_fga                   float64
visitor_fgp                   float64
visitor_ftm                   float64
visitor_fta                   float64
visitor_ftp                   float64
visitor_tpm                   float64
visitor_tpa                   float64
visitor_tpp                   float64
visitor_offReb                float64
visitor_defReb                float64
visitor_totReb                float64
visitor_assists               float64
visitor_pFouls                float64
visitor_steals                float64
visitor_turnovers             float64
visitor_blocks                float64
visitor_plusMinus             float64
visitor_min                    object
game_id                         int64
visitor_team                   object
home_fastBreakPoints          float64
home_pointsInPaint            float64
home_biggestLead              float64
home_secondChancePoints       float64
home_pointsOffTurnovers       float64
home_longestRun               float64
home_points                   float64
home_fgm                      float64
home_fga                      float64
home_fgp                      float64
home_ftm                      float64
home_fta                      float64
home_ftp                      float64
home_tpm                      float64
home_tpa                      float64
home_tpp                      float64
home_offReb                   float64
home_defReb                   float64
home_totReb                   float64
home_assists                  float64
home_pFouls                   float64
home_steals                   float64
home_turnovers                float64
home_blocks                   float64
home_plusMinus                float64
home_min                       object
home_team                      object
dtype: object

In [198]:
# Convert values in percentage columns to decimal form
game_df[['visitor_ftp', 'visitor_fgp', 'visitor_tpp', 'home_ftp', 'home_fgp','home_tpp']] = game_df[
    ['visitor_ftp', 
     'visitor_fgp', 
     'visitor_tpp', 
     'home_ftp', 
     'home_fgp',
     'home_tpp']
    ].apply(lambda x: x / 100)

In [199]:
# Drop game_id column
game_df = game_df.drop(columns='game_id')

In [200]:
# Based on the column data and the fact that the home_team has the same missing data as the visitor_team
# A function should be created to fill all the Null values with the average of those columns
# Later will see if this affects how well the machine learning model works

def fillNullCols(df):
    # Find all data type 'int' or 'float' columns that have Null values
    df.select_dtypes(include=['int', 'float'])

    # Looks at the total percentage of null values in each columns
    null_percentage = (df.isnull().sum() / len(df)) * 100

    # Rule of thumb: Moderate Null Percentage (10-30%)
    # Filling the null values with an appropriate value (like the mean, median, or mode) is often better in this range, especially if the column is critical for analysis

    # Get columns from null_percentage with at least 20% with null values
    null_columns = null_percentage[null_percentage >= 0.2].index

    # Fill rows with the mode of the column
    for column in null_columns:
        mode_fill_value = df[column].mode()[0]
        df[column] = df[column].fillna(mode_fill_value)

    return df

# Create new data frame
stats_df = fillNullCols(game_df)
stats_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,18.0,34.0,2.0,11.0,20.0,9.0,97.0,34.0,82.0,0.415,...,37.0,43.0,33.0,25.0,8.0,20.0,7.0,24.0,240:00,Atlanta Hawks
1,25.0,46.0,12.0,11.0,18.0,9.0,107.0,40.0,90.0,0.444,...,39.0,44.0,31.0,22.0,10.0,17.0,10.0,11.0,240:00,Atlanta Hawks
2,15.0,36.0,3.0,11.0,10.0,9.0,101.0,37.0,102.0,0.363,...,40.0,53.0,23.0,20.0,4.0,11.0,9.0,1.0,240:00,Atlanta Hawks
3,8.0,36.0,0.0,11.0,6.0,9.0,72.0,28.0,88.0,0.318,...,46.0,49.0,20.0,16.0,7.0,15.0,15.0,17.0,240:00,Atlanta Hawks
4,8.0,32.0,10.0,11.0,9.0,9.0,83.0,29.0,77.0,0.377,...,38.0,51.0,30.0,17.0,13.0,12.0,3.0,27.0,240:00,Atlanta Hawks

In [201]:
# Create target columns 'total_points'
stats_df['total_points'] = stats_df['visitor_points'] + stats_df['home_points']
stats_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team,total_points
0,18.0,34.0,2.0,11.0,20.0,9.0,97.0,34.0,82.0,0.415,...,43.0,33.0,25.0,8.0,20.0,7.0,24.0,240:00,Atlanta Hawks,218.0
1,25.0,46.0,12.0,11.0,18.0,9.0,107.0,40.0,90.0,0.444,...,44.0,31.0,22.0,10.0,17.0,10.0,11.0,240:00,Atlanta Hawks,225.0
2,15.0,36.0,3.0,11.0,10.0,9.0,101.0,37.0,102.0,0.363,...,53.0,23.0,20.0,4.0,11.0,9.0,1.0,240:00,Atlanta Hawks,203.0
3,8.0,36.0,0.0,11.0,6.0,9.0,72.0,28.0,88.0,0.318,...,49.0,20.0,16.0,7.0,15.0,15.0,17.0,240:00,Atlanta Hawks,161.0
4,8.0,32.0,10.0,11.0,9.0,9.0,83.0,29.0,77.0,0.377,...,51.0,30.0,17.0,13.0,12.0,3.0,27.0,240:00,Atlanta Hawks,193.0

In [202]:
# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column].sort_values(ascending=False)
correlations

total_points                  1.000000
visitor_points                0.844452
home_points                   0.829460
visitor_fgm                   0.725605
home_fgm                      0.684140
visitor_fgp                   0.525908
visitor_assists               0.506038
home_assists                  0.494517
visitor_tpm                   0.458288
visitor_fga                   0.440052
home_tpm                      0.427785
home_fga                      0.419075
visitor_pointsInPaint         0.379618
visitor_tpp                   0.372084
home_fgp                      0.324731
home_tpp                      0.322302
home_pointsInPaint            0.304784
visitor_tpa                   0.303786
home_tpa                      0.288918
home_ftm                      0.272157
visitor_ftm                   0.264036
home_fta                      0.236013
visitor_fta                   0.227624
visitor_pFouls                0.172668
home_secondChancePoints       0.157353
home_pFouls                   0.146750
home_ftp                      0.139523
visitor_ftp                   0.132419
visitor_pointsOffTurnovers    0.127791
visitor_secondChancePoints    0.111050
home_fastBreakPoints          0.109754
visitor_fastBreakPoints       0.103365
home_offReb                   0.056006
visitor_plusMinus             0.045739
visitor_offReb                0.016603
home_pointsOffTurnovers      -0.000221
visitor_longestRun           -0.020079
home_longestRun              -0.022552
visitor_blocks               -0.034500
visitor_steals               -0.037400
home_plusMinus               -0.045739
home_totReb                  -0.056880
home_blocks                  -0.057088
home_turnovers               -0.063064
home_steals                  -0.064880
visitor_biggestLead          -0.068825
visitor_totReb               -0.073712
visitor_defReb               -0.100230
visitor_turnovers            -0.101313
home_defReb                  -0.106705
home_biggestLead             -0.110593
Name: total_points, dtype: float64

In [241]:
# Set target column
target_column = 'total_points'

# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column]

# Set conditions to find feature columns
feature_columns = correlations[correlations > 0.4]

# Create new data frame with chosen feature columns
new_df = stats_df[feature_columns.index]

# Add 'visitor_team' and 'home_team' to the new DataFrame
new_df = pd.concat([stats_df[['home_team', 'visitor_team']], new_df], axis=1)
new_df

,home_team,visitor_team,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_tpm,visitor_assists,home_points,home_fgm,home_fga,home_tpm,home_assists,total_points
0,Atlanta Hawks,Boston Celtics,97.0,34.0,82.0,0.415,9.0,23.0,121.0,45.0,80.0,12.0,33.0,218.0
1,Atlanta Hawks,Boston Celtics,107.0,40.0,90.0,0.444,11.0,26.0,118.0,46.0,88.0,17.0,31.0,225.0
2,Atlanta Hawks,Boston Celtics,101.0,37.0,102.0,0.363,11.0,27.0,102.0,35.0,86.0,5.0,23.0,203.0
3,Atlanta Hawks,Boston Celtics,72.0,28.0,88.0,0.318,5.0,16.0,89.0,32.0,82.0,11.0,20.0,161.0
4,Atlanta Hawks,Boston Celtics,83.0,29.0,77.0,0.377,7.0,19.0,110.0,42.0,96.0,14.0,30.0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,Toronto Raptors,Washington Wizards,113.0,35.0,76.0,0.461,17.0,23.0,95.0,34.0,95.0,7.0,20.0,208.0
3054,Washington Wizards,Utah Jazz,127.0,48.0,90.0,0.533,10.0,24.0,116.0,47.0,93.0,7.0,28.0,243.0
3055,Utah Jazz,Washington Wizards,121.0,44.0,88.0,0.500,16.0,27.0,112.0,44.0,94.0,14.0,33.0,233.0
3056,Utah Jazz,Washington Wizards,124.0,48.0,98.0,0.490,15.0,32.0,128.0,48.0,87.0,14.0,26.0,252.0
3057,Washington Wizards,Utah Jazz,120.0,42.0,86.0,0.488,16.0,16.0,112.0,46.0,82.0,7.0,20.0,232.0

In [236]:
new_df.isnull().sum()

home_team         0
visitor_team      0
visitor_points    1
visitor_fgm       1
home_points       1
home_fgm          1
total_points      1
dtype: int64

In [253]:
new_df = new_df.dropna()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3057 entries, 0 to 3057
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   home_team        3057 non-null   object
 1   visitor_team     3057 non-null   object
 2   visitor_points   3057 non-null   float64
 3   visitor_fgm      3057 non-null   float64
 4   visitor_fga      3057 non-null   float64
 5   visitor_fgp      3057 non-null   float64
 6   visitor_tpm      3057 non-null   float64
 7   visitor_assists  3057 non-null   float64
 8   home_points      3057 non-null   float64
 9   home_fgm         3057 non-null   float64
 10  home_fga         3057 non-null   float64
 11  home_tpm         3057 non-null   float64
 12  home_assists     3057 non-null   float64
 13  total_points     3057 non-null   float64
dtypes: float64(12), object(2)
memory usage: 358.2+ KB

In [234]:
# # Apply one-hot encoding and convert to booleans to integers
# encoded_df = pd.get_dummies(new_df, columns=['visitor_team', 'home_team'])

# # Convert only the binary columns to integers
# encoded_df = encoded_df.apply(lambda x: x.astype(int) if x.dtype == 'bool' else x)

# # Display
# encoded_df

In [255]:

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Apply one-hot encoding and convert to booleans to integers
encoded_df = pd.get_dummies(new_df, columns=['visitor_team', 'home_team'])

# Convert only the binary columns to integers
encoded_df = encoded_df.apply(lambda x: x.astype(int) if x.dtype == 'bool' else x)

# Create instance of scaler
scaler = MinMaxScaler()

# X = scaler.fit_transform(encoded_df.drop(columns=['total_points', 'home_points', 'visitor_points']))
X = encoded_df.drop(columns=['total_points', 'home_points', 'visitor_points'])
y = encoded_df['total_points']

X_scaled = scaler.fit_transform(X)

X_df = pd.DataFrame(X_scaled, columns=X.columns)

# Splitting into testing/train data
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

# Create decision tree regression instance
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit model
model = model.fit(X_train, y_train)


# # Making predictions using scaled data
predictions = model.predict(X_test)

# # Print predicted price for tested features
predictions

array([225.58, 226.78, 257.58, 236.79, 197.51, 202.44, 207.62, 227.81,
       224.23, 238.67, 234.06, 215.88, 205.79, 207.67, 228.42, 198.83,
       236.15, 207.75, 201.51, 200.63, 226.05, 183.83, 247.41, 202.02,
       232.65, 255.8 , 225.49, 226.42, 228.8 , 197.4 , 185.75, 236.28,
       221.97, 203.26, 218.08, 218.53, 200.65, 200.36, 191.52, 224.39,
       204.2 , 227.5 , 222.88, 254.21, 219.91, 210.22, 255.86, 203.76,
       211.81, 203.83, 219.05, 231.67, 239.54, 216.47, 239.68, 219.82,
       224.53, 215.35, 239.26, 209.9 , 211.45, 207.02, 188.85, 226.25,
       248.32, 246.93, 255.27, 210.14, 242.53, 240.14, 245.65, 240.46,
       231.17, 215.8 , 212.38, 223.3 , 225.22, 196.03, 220.32, 222.81,
       203.79, 216.02, 201.55, 229.15, 246.76, 241.32, 273.98, 204.21,
       203.35, 179.11, 203.21, 195.27, 239.38, 226.44, 208.82, 213.13,
       230.81, 253.16, 211.37, 240.6 , 200.36, 232.48, 256.15, 215.91,
       200.29, 197.78, 269.84, 218.29, 235.98, 215.86, 209.99, 226.91,
       213.3 , 201.85, 252.83, 230.88, 224.91, 220.09, 178.72, 207.9 ,
       187.  , 209.28, 233.15, 223.72, 227.48, 198.18, 189.72, 223.12,
       230.6 , 256.77, 216.44, 219.21, 199.44, 229.32, 236.06, 220.72,
       193.51, 238.86, 229.37, 184.23, 206.42, 252.78, 240.85, 219.88,
       229.58, 204.44, 249.86, 208.64, 261.25, 246.85, 203.73, 228.04,
       228.7 , 223.42, 216.12, 225.46, 208.51, 224.86, 200.88, 200.62,
       228.22, 205.57, 245.04, 223.56, 209.31, 204.96, 238.17, 209.35,
       255.2 , 271.56, 224.39, 204.58, 216.28, 219.72, 224.27, 218.01,
       247.42, 214.6 , 227.87, 230.61, 207.09, 242.87, 218.66, 190.19,
       227.98, 167.27, 222.14, 235.22, 218.96, 219.25, 200.6 , 235.61,
       221.13, 207.74, 239.92, 244.26, 204.43, 230.79, 221.37, 206.12,
       216.88, 235.26, 239.62, 212.39, 212.08, 212.25, 211.8 , 219.55,
       201.51, 201.98, 185.04, 252.6 , 272.58, 211.37, 208.24, 178.2 ,
       195.56, 192.44, 218.75, 223.48, 231.72, 203.2 , 282.11, 220.09,
       205.99, 195.75, 218.05, 207.76, 240.21, 207.38, 217.06, 193.03,
       230.83, 248.82, 226.98, 215.28, 176.09, 215.83, 161.67, 226.33,
       230.73, 205.17, 207.77, 209.37, 223.14, 235.77, 215.4 , 252.61,
       228.24, 207.43, 234.83, 214.55, 214.81, 229.73, 180.2 , 228.66,
       201.99, 219.1 , 195.15, 251.09, 228.77, 225.57, 230.15, 235.76,
       236.52, 206.05, 217.27, 227.33, 227.05, 209.42, 229.4 , 202.19,
       223.2 , 197.92, 230.17, 206.82, 231.49, 197.11, 209.93, 206.15,
       171.02, 216.75, 172.19, 225.82, 187.38, 219.97, 221.19, 214.52,
       219.65, 232.59, 229.92, 227.44, 204.24, 211.84, 218.77, 209.43,
       194.32, 200.24, 226.  , 225.46, 210.63, 212.8 , 210.41, 240.54,
       224.03, 200.92, 255.38, 241.56, 202.42, 222.89, 206.21, 223.79,
       207.98, 206.3 , 249.29, 238.8 , 210.84, 221.94, 211.28, 203.84,
       220.28, 202.54, 217.14, 231.77, 220.75, 197.34, 197.71, 226.44,
       184.81, 205.5 , 232.51, 204.09, 216.08, 233.86, 225.27, 229.12,
       201.25, 237.71, 221.38, 233.85, 150.92, 229.83, 221.92, 223.85,
       232.45, 185.88, 196.11, 239.24, 197.37, 219.41, 219.79, 230.53,
       214.2 , 184.84, 251.86, 220.47, 237.1 , 195.97, 231.41, 207.06,
       219.39, 218.38, 243.26, 199.77, 223.  , 220.19, 228.68, 211.91,
       228.73, 222.36, 212.01, 225.83, 188.4 , 215.86, 201.68, 227.77,
       193.79, 232.12, 197.34, 214.44, 251.53, 218.13, 192.05, 220.43,
       233.05, 232.62, 219.7 , 228.49, 213.04, 202.45, 236.86, 198.6 ,
       200.68, 188.19, 222.25, 195.9 , 195.57, 218.93, 205.2 , 201.59,
       197.14, 222.22, 215.22, 228.46, 185.95, 238.2 , 243.62, 215.71,
       185.39, 173.01, 225.49, 236.  , 202.61, 189.46, 233.29, 191.2 ,
       166.86, 191.17, 227.02, 184.4 , 233.84, 224.1 , 240.04, 204.09,
       204.21, 239.41, 220.03, 237.5 , 229.47, 209.34, 262.09, 154.28,
       193.14, 225.04, 206.88, 200.98, 217.44, 202.1 , 227.16, 223.02,
       221.62, 233.05, 176.95, 184.67, 211.71, 206.94, 212.94, 219.2 ,
       157.31, 194.57, 209.22, 205.72, 217.85, 209.88, 188.02, 201.39,
       231.48, 236.88, 264.72, 204.09, 198.13, 211.61, 242.8 , 189.76,
       193.53, 221.86, 203.91, 222.88, 211.45, 197.93, 233.86, 185.47,
       220.97, 208.83, 219.68, 223.05, 227.07, 205.03, 207.82, 205.51,
       225.59, 210.62, 212.82, 225.25, 219.03, 200.49, 227.05, 251.58,
       210.93, 218.7 , 234.9 , 208.04, 210.41, 230.42, 251.71, 208.2 ,
       212.73, 215.13, 223.86, 217.91, 169.  , 199.63, 207.72, 204.09,
       222.58, 207.84, 209.62, 204.36, 201.7 , 199.17, 244.23, 192.73,
       227.73, 198.08, 220.19, 224.9 , 230.08, 259.5 , 221.04, 217.04,
       234.43, 208.24, 199.9 , 213.46, 213.49, 211.73, 221.78, 206.18,
       216.13, 216.46, 186.79, 264.15, 251.77, 243.96, 214.52, 211.62,
       222.6 , 201.33, 222.56, 235.25, 224.69, 198.09, 216.54, 224.82,
       251.95, 216.28, 236.86, 224.31, 184.8 , 224.08, 204.93, 230.76,
       183.91, 204.23, 213.5 , 229.57, 218.01, 219.38, 256.42, 215.34,
       191.14, 216.1 , 215.53, 192.72, 206.47, 215.9 , 194.97, 220.14,
       211.31, 269.42, 215.11, 224.  , 212.75, 218.79, 214.02, 230.09,
       249.16, 225.81, 209.85, 170.53, 204.99, 214.14, 194.39, 218.36,
       167.87, 236.65, 199.13, 227.3 , 230.96, 212.29, 226.05, 198.15,
       235.52, 238.25, 224.69, 228.72, 214.94, 240.81, 258.39, 230.42,
       240.15, 226.12, 218.53, 218.51, 209.67, 240.78, 204.11, 213.91,
       215.03, 245.09, 228.7 , 195.95])

In [256]:
# Evaluate the model
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")

Mean Absolute Error: 8.038137254901962
Mean Squared Error: 102.12137875816995
R^2 Score: 0.7908077110602924

In [240]:
# Define the home and visitor teams
home_team = input("Enter Away Team: ")  # Replace with desired home team
visitor_team = input("Enter Home Team: ")  # Replace with desired visitor team

# Create a new data instance with zeros for all one-hot columns
input_data = {col: 0 for col in X_df.columns}
input_data[f'home_team_{home_team}'] = 1
input_data[f'visitor_team_{visitor_team}'] = 1

# Convert to DataFrame
input_df = pd.DataFrame([input_data])

# Apply the same MinMaxScaler used on X_df
input_scaled = scaler.transform(input_df)

# Predict total points
predicted_total_points = model.predict(input_scaled)[0]
print(f"Predicted Total Points: {predicted_total_points}")

Predicted Total Points: 159.63

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

# Winner Prediction

In [260]:
# Create a column to check if the home team won
encoded_df['home_win'] = encoded_df.apply(
    lambda row: 1 if row['home_points'] > row['visitor_points'] else 0,
    axis=1
)
encoded_df.head()

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_tpm,visitor_assists,home_points,home_fgm,home_fga,home_tpm,...,home_team_Orlando Magic,home_team_Philadelphia 76ers,home_team_Phoenix Suns,home_team_Portland Trail Blazers,home_team_Sacramento Kings,home_team_San Antonio Spurs,home_team_Toronto Raptors,home_team_Utah Jazz,home_team_Washington Wizards,home_win
0,97.0,34.0,82.0,0.415,9.0,23.0,121.0,45.0,80.0,12.0,...,0,0,0,0,0,0,0,0,0,1
1,107.0,40.0,90.0,0.444,11.0,26.0,118.0,46.0,88.0,17.0,...,0,0,0,0,0,0,0,0,0,1
2,101.0,37.0,102.0,0.363,11.0,27.0,102.0,35.0,86.0,5.0,...,0,0,0,0,0,0,0,0,0,1
3,72.0,28.0,88.0,0.318,5.0,16.0,89.0,32.0,82.0,11.0,...,0,0,0,0,0,0,0,0,0,1
4,83.0,29.0,77.0,0.377,7.0,19.0,110.0,42.0,96.0,14.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

scaler = MinMaxScaler()

X = scaler.fit_transform(encoded_df.drop(columns=['home_win', 'home_points', 'total_points', 'visitor_points']))

X_df = pd.DataFrame(X, columns=encoded_df.drop(columns=['home_win', 'home_points', 'total_points', 'visitor_points']).columns)
y = encoded_df['home_win']

# Splitting into testing/train data
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

# Create decision tree regression instance
model = DecisionTreeClassifier()

# Fit model
model = model.fit(X_train, y_train)

# Making predictions using scaled data
predictions = model.predict(X_test)

# Print predicted price for tested features
predictions

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [267]:
# Define the home and visitor teams
home_team = input("Enter Away Team: ")  # Replace with desired home team
visitor_team = input("Enter Home Team: ")  # Replace with desired visitor team

# Create a new data instance with zeros for all one-hot columns
input_data = {col: 0 for col in X_df.columns}
input_data[f'home_team_{home_team}'] = 1
input_data[f'visitor_team_{visitor_team}'] = 1

# Convert to DataFrame
input_df = pd.DataFrame([input_data])

# Apply the same MinMaxScaler used on X_df
input_scaled = scaler.transform(input_df)

# Predict total points
predicted_winner = model.predict(input_scaled)[0]

winning_team = home_team if  predicted_winner == 1 else visitor_team
print("Predicted Winner:", winning_team)

Predicted Winner: Miami Heat

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [266]:
print("Accuracy:", accuracy_score(y_test, predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
print("Classification Report:\n", classification_report(y_test, predictions))

Accuracy: 0.7467320261437909
Confusion Matrix:
 [[217  73]
 [ 82 240]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.75      0.74       290
           1       0.77      0.75      0.76       322

    accuracy                           0.75       612
   macro avg       0.75      0.75      0.75       612
weighted avg       0.75      0.75      0.75       612