In [424]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [425]:
game_df = pd.read_csv('./data/gameStatistics.csv') # change path to ./data/gameStatistics contains the game_ids when cleaned properly
game_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,NaN,NaN,NaN,NaN,NaN,NaN,120,46,87,52.9,...,26,38,21,16,7,9,8,-2,240:00,Boston Celtics
1,NaN,NaN,NaN,NaN,NaN,NaN,123,51,104,49.0,...,34,43,28,15,7,12,6,-1,240:00,Boston Celtics
2,NaN,NaN,NaN,NaN,NaN,NaN,93,37,89,41.6,...,39,50,27,14,15,13,7,30,240:00,Boston Celtics
3,NaN,NaN,NaN,NaN,NaN,NaN,125,49,93,52.7,...,36,49,24,13,8,9,2,-8,240:00,Atlanta Hawks
4,NaN,NaN,NaN,NaN,NaN,NaN,116,38,75,50.7,...,25,45,35,17,16,16,2,1,240:00,Atlanta Hawks

In [426]:
game_df.describe()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus
count,0.0,0.0,0.0,0.0,0.0,0.0,299.000000,299.000000,299.000000,299.000000,...,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,114.133779,41.876254,88.471572,47.414716,...,35.436120,10.468227,32.806020,43.274247,25.735786,18.060201,7.123746,13.705686,4.725753,-3.197324
std,NaN,NaN,NaN,NaN,NaN,NaN,13.687628,5.682429,8.393132,5.356040,...,8.172665,3.906821,5.609421,6.955156,5.237362,4.386112,3.003589,4.210127,2.442295,16.302237
min,NaN,NaN,NaN,NaN,NaN,NaN,77.000000,21.000000,43.000000,34.300000,...,10.300000,2.000000,16.000000,21.000000,9.000000,8.000000,0.000000,3.000000,0.000000,-52.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,105.000000,38.000000,84.000000,43.450000,...,29.650000,7.000000,29.000000,38.000000,22.000000,15.000000,5.000000,11.000000,3.000000,-13.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,113.000000,41.000000,89.000000,47.300000,...,35.000000,10.000000,32.000000,43.000000,25.000000,18.000000,7.000000,14.000000,4.000000,-3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,123.000000,45.000000,93.000000,51.100000,...,40.500000,13.000000,37.000000,48.000000,29.000000,21.000000,9.000000,16.000000,6.000000,8.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,157.000000,65.000000,115.000000,65.000000,...,61.100000,22.000000,48.000000,65.000000,41.000000,32.000000,16.000000,33.000000,13.000000,35.000000

In [427]:
game_df.dtypes

visitor_fastBreakPoints       float64
visitor_pointsInPaint         float64
visitor_biggestLead           float64
visitor_secondChancePoints    float64
visitor_pointsOffTurnovers    float64
visitor_longestRun            float64
visitor_points                  int64
visitor_fgm                     int64
visitor_fga                     int64
visitor_fgp                   float64
visitor_ftm                     int64
visitor_fta                     int64
visitor_ftp                   float64
visitor_tpm                     int64
visitor_tpa                     int64
visitor_tpp                   float64
visitor_offReb                  int64
visitor_defReb                  int64
visitor_totReb                  int64
visitor_assists                 int64
visitor_pFouls                  int64
visitor_steals                  int64
visitor_turnovers               int64
visitor_blocks                  int64
visitor_plusMinus               int64
visitor_min                    object
game_id                         int64
visitor_team                   object
home_fastBreakPoints          float64
home_pointsInPaint            float64
home_biggestLead              float64
home_secondChancePoints       float64
home_pointsOffTurnovers       float64
home_longestRun               float64
home_points                     int64
home_fgm                        int64
home_fga                        int64
home_fgp                      float64
home_ftm                        int64
home_fta                        int64
home_ftp                      float64
home_tpm                        int64
home_tpa                        int64
home_tpp                      float64
home_offReb                     int64
home_defReb                     int64
home_totReb                     int64
home_assists                    int64
home_pFouls                     int64
home_steals                     int64
home_turnovers                  int64
home_blocks                     int64
home_plusMinus                  int64
home_min                       object
home_team                      object
dtype: object

In [428]:
# Convert values in percentage columns to decimal form
game_df[['visitor_ftp', 'visitor_fgp', 'visitor_tpp', 'home_ftp', 'home_fgp','home_tpp']] = game_df[
    ['visitor_ftp', 
     'visitor_fgp', 
     'visitor_tpp', 
     'home_ftp', 
     'home_fgp',
     'home_tpp']
    ].apply(lambda x: x / 100)

In [429]:
# Drop irrelevant columns
game_df = game_df.drop(columns=['game_id','visitor_fastBreakPoints', 'visitor_pointsInPaint',
       'visitor_biggestLead', 'visitor_secondChancePoints',
       'visitor_pointsOffTurnovers', 'visitor_longestRun','visitor_plusMinus',
       'visitor_min','home_fastBreakPoints',
       'home_pointsInPaint', 'home_biggestLead', 'home_secondChancePoints',
       'home_pointsOffTurnovers', 'home_longestRun','home_plusMinus', 'home_min',])

# Display
game_df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,0.289,12,26,38,21,16,7,9,8,Boston Celtics
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,0.389,9,34,43,28,15,7,12,6,Boston Celtics
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,0.327,11,39,50,27,14,15,13,7,Boston Celtics
3,125,49,93,0.527,10,11,0.909,17,49,0.347,...,0.317,13,36,49,24,13,8,9,2,Atlanta Hawks
4,116,38,75,0.507,22,27,0.815,18,45,0.400,...,0.313,20,25,45,35,17,16,16,2,Atlanta Hawks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,112,42,108,0.389,18,21,0.857,10,48,0.208,...,0.200,12,47,59,24,18,8,13,9,Chicago Bulls
295,144,51,93,0.548,21,24,0.875,21,43,0.488,...,0.476,3,33,36,32,20,7,17,4,Chicago Bulls
296,119,45,93,0.484,17,21,0.810,12,38,0.316,...,0.286,14,37,51,25,17,8,23,2,Chicago Bulls
297,92,35,89,0.393,15,22,0.682,7,34,0.206,...,0.317,10,39,49,33,17,10,6,6,Dallas Mavericks
298,105,38,77,0.494,15,23,0.652,14,35,0.400,...,0.389,11,31,42,28,15,14,9,5,Chicago Bulls

# Filter Data Frame for Chosen Teams

In [430]:
game_df[['home_team', 'visitor_team']]

            home_team         visitor_team
0      Boston Celtics        Atlanta Hawks
1      Boston Celtics        Atlanta Hawks
2      Boston Celtics        Atlanta Hawks
3       Atlanta Hawks       Boston Celtics
4       Atlanta Hawks       Boston Celtics
..                ...                  ...
294     Chicago Bulls  Cleveland Cavaliers
295     Chicago Bulls  Cleveland Cavaliers
296     Chicago Bulls     Dallas Mavericks
297  Dallas Mavericks        Chicago Bulls
298     Chicago Bulls      Detroit Pistons

[299 rows x 2 columns]

In [431]:
# Define the home and visitor teams
home_team = input("Enter Away Team: ")  # Replace with desired home team
visitor_team = input("Enter Home Team: ")  # Replace with desired visitor team

# Filter data frame based on previous condition
filtered_df = game_df[(game_df['home_team'] == home_team) & (game_df['visitor_team'] == visitor_team)]

# Drop home and visitor columns
filtered_df = filtered_df.drop(columns=['home_team', 'visitor_team'])

# Update column names to match team stats
update_cols = []
for col in filtered_df.columns:
    if f"visitor_" in col:
        update_cols.append(col.replace('visitor', visitor_team))
    elif f"home_" in col:
        update_cols.append(col.replace('home', home_team))
    else:
        update_cols.append(col)

filtered_df.columns = update_cols

# Display
filtered_df.head()

,Atlanta Hawks_points,Atlanta Hawks_fgm,Atlanta Hawks_fga,Atlanta Hawks_fgp,Atlanta Hawks_ftm,Atlanta Hawks_fta,Atlanta Hawks_ftp,Atlanta Hawks_tpm,Atlanta Hawks_tpa,Atlanta Hawks_tpp,...,Boston Celtics_tpa,Boston Celtics_tpp,Boston Celtics_offReb,Boston Celtics_defReb,Boston Celtics_totReb,Boston Celtics_assists,Boston Celtics_pFouls,Boston Celtics_steals,Boston Celtics_turnovers,Boston Celtics_blocks
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,38,0.289,12,26,38,21,16,7,9,8
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,36,0.389,9,34,43,28,15,7,12,6
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,55,0.327,11,39,50,27,14,15,13,7

# Prepare Machine Learning Model

In [432]:
# Create a column to check if the home team won
stats_df = filtered_df.copy()
stats_df['home_win'] = stats_df.apply(
    lambda row: 1 if row[f'{home_team}_points'] > row[f'{visitor_team}_points'] else 0,
    axis=1
)
stats_df.head()

,Atlanta Hawks_points,Atlanta Hawks_fgm,Atlanta Hawks_fga,Atlanta Hawks_fgp,Atlanta Hawks_ftm,Atlanta Hawks_fta,Atlanta Hawks_ftp,Atlanta Hawks_tpm,Atlanta Hawks_tpa,Atlanta Hawks_tpp,...,Boston Celtics_tpp,Boston Celtics_offReb,Boston Celtics_defReb,Boston Celtics_totReb,Boston Celtics_assists,Boston Celtics_pFouls,Boston Celtics_steals,Boston Celtics_turnovers,Boston Celtics_blocks,home_win
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,0.289,12,26,38,21,16,7,9,8,0
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,0.389,9,34,43,28,15,7,12,6,0
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,0.327,11,39,50,27,14,15,13,7,1

In [433]:
# Set target column
target_column = 'home_win'

# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column].sort_values(ascending=False)
correlations

home_win                    1.000000
Atlanta Hawks_steals        1.000000
Boston Celtics_steals       1.000000
Atlanta Hawks_ftp           0.998876
Boston Celtics_fgp          0.998876
Boston Celtics_tpa          0.995402
Boston Celtics_fga          0.981981
Atlanta Hawks_turnovers     0.977356
Boston Celtics_totReb       0.909935
Boston Celtics_tpm          0.904194
Atlanta Hawks_ftm           0.821995
Boston Celtics_defReb       0.792406
Boston Celtics_fgm          0.755929
Boston Celtics_turnovers    0.693375
Boston Celtics_points       0.654654
Atlanta Hawks_defReb        0.381246
Atlanta Hawks_fta           0.381246
Boston Celtics_assists      0.381246
Boston Celtics_offReb       0.188982
Boston Celtics_blocks       0.000000
Boston Celtics_tpp         -0.137253
Atlanta Hawks_fga          -0.403890
Boston Celtics_ftp         -0.464107
Atlanta Hawks_blocks       -0.500000
Atlanta Hawks_totReb       -0.576557
Atlanta Hawks_assists      -0.609994
Atlanta Hawks_tpa          -0.792406
Boston Celtics_ftm         -0.832240
Atlanta Hawks_tpp          -0.854486
Boston Celtics_pFouls      -0.866025
Atlanta Hawks_fgm          -0.935857
Atlanta Hawks_fgp          -0.940518
Boston Celtics_fta         -0.970725
Atlanta Hawks_tpm          -0.970725
Atlanta Hawks_offReb       -0.977356
Atlanta Hawks_pFouls       -0.981981
Atlanta Hawks_points       -0.995871
Name: home_win, dtype: float64

In [434]:
# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column]

# Set conditions to find feature columns
feature_columns = correlations[correlations > -1]

# Create new data frame with chosen feature columns
new_df = stats_df[feature_columns.index]
new_df

,Atlanta Hawks_points,Atlanta Hawks_fgm,Atlanta Hawks_fga,Atlanta Hawks_fgp,Atlanta Hawks_ftm,Atlanta Hawks_fta,Atlanta Hawks_ftp,Atlanta Hawks_tpm,Atlanta Hawks_tpa,Atlanta Hawks_tpp,...,Boston Celtics_tpp,Boston Celtics_offReb,Boston Celtics_defReb,Boston Celtics_totReb,Boston Celtics_assists,Boston Celtics_pFouls,Boston Celtics_steals,Boston Celtics_turnovers,Boston Celtics_blocks,home_win
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,0.289,12,26,38,21,16,7,9,8,0
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,0.389,9,34,43,28,15,7,12,6,0
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,0.327,11,39,50,27,14,15,13,7,1

In [435]:
new_df.isnull().sum()

Atlanta Hawks_points        0
Atlanta Hawks_fgm           0
Atlanta Hawks_fga           0
Atlanta Hawks_fgp           0
Atlanta Hawks_ftm           0
Atlanta Hawks_fta           0
Atlanta Hawks_ftp           0
Atlanta Hawks_tpm           0
Atlanta Hawks_tpa           0
Atlanta Hawks_tpp           0
Atlanta Hawks_offReb        0
Atlanta Hawks_defReb        0
Atlanta Hawks_totReb        0
Atlanta Hawks_assists       0
Atlanta Hawks_pFouls        0
Atlanta Hawks_steals        0
Atlanta Hawks_turnovers     0
Atlanta Hawks_blocks        0
Boston Celtics_points       0
Boston Celtics_fgm          0
Boston Celtics_fga          0
Boston Celtics_fgp          0
Boston Celtics_ftm          0
Boston Celtics_fta          0
Boston Celtics_ftp          0
Boston Celtics_tpm          0
Boston Celtics_tpa          0
Boston Celtics_tpp          0
Boston Celtics_offReb       0
Boston Celtics_defReb       0
Boston Celtics_totReb       0
Boston Celtics_assists      0
Boston Celtics_pFouls       0
Boston Celtics_steals       0
Boston Celtics_turnovers    0
Boston Celtics_blocks       0
home_win                    0
dtype: int64

In [436]:
new_df.columns

Index(['Atlanta Hawks_points', 'Atlanta Hawks_fgm', 'Atlanta Hawks_fga',
       'Atlanta Hawks_fgp', 'Atlanta Hawks_ftm', 'Atlanta Hawks_fta',
       'Atlanta Hawks_ftp', 'Atlanta Hawks_tpm', 'Atlanta Hawks_tpa',
       'Atlanta Hawks_tpp', 'Atlanta Hawks_offReb', 'Atlanta Hawks_defReb',
       'Atlanta Hawks_totReb', 'Atlanta Hawks_assists', 'Atlanta Hawks_pFouls',
       'Atlanta Hawks_steals', 'Atlanta Hawks_turnovers',
       'Atlanta Hawks_blocks', 'Boston Celtics_points', 'Boston Celtics_fgm',
       'Boston Celtics_fga', 'Boston Celtics_fgp', 'Boston Celtics_ftm',
       'Boston Celtics_fta', 'Boston Celtics_ftp', 'Boston Celtics_tpm',
       'Boston Celtics_tpa', 'Boston Celtics_tpp', 'Boston Celtics_offReb',
       'Boston Celtics_defReb', 'Boston Celtics_totReb',
       'Boston Celtics_assists', 'Boston Celtics_pFouls',
       'Boston Celtics_steals', 'Boston Celtics_turnovers',
       'Boston Celtics_blocks', 'home_win'],
      dtype='object')

In [437]:
new_df = new_df.dropna()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Atlanta Hawks_points      3 non-null      int64
 1   Atlanta Hawks_fgm         3 non-null      int64
 2   Atlanta Hawks_fga         3 non-null      int64
 3   Atlanta Hawks_fgp         3 non-null      float64
 4   Atlanta Hawks_ftm         3 non-null      int64
 5   Atlanta Hawks_fta         3 non-null      int64
 6   Atlanta Hawks_ftp         3 non-null      float64
 7   Atlanta Hawks_tpm         3 non-null      int64
 8   Atlanta Hawks_tpa         3 non-null      int64
 9   Atlanta Hawks_tpp         3 non-null      float64
 10  Atlanta Hawks_offReb      3 non-null      int64
 11  Atlanta Hawks_defReb      3 non-null      int64
 12  Atlanta Hawks_totReb      3 non-null      int64
 13  Atlanta Hawks_assists     3 non-null      int64
 14  Atlanta Hawks_pFouls      3 non-null      int64
 15  Atlanta Hawks_steals      3 non-null      int64
 16  Atlanta Hawks_turnovers   3 non-null      int64
 17  Atlanta Hawks_blocks      3 non-null      int64
 18  Boston Celtics_points     3 non-null      int64
 19  Boston Celtics_fgm        3 non-null      int64
 20  Boston Celtics_fga        3 non-null      int64
 21  Boston Celtics_fgp        3 non-null      float64
 22  Boston Celtics_ftm        3 non-null      int64
 23  Boston Celtics_fta        3 non-null      int64
 24  Boston Celtics_ftp        3 non-null      float64
 25  Boston Celtics_tpm        3 non-null      int64
 26  Boston Celtics_tpa        3 non-null      int64
 27  Boston Celtics_tpp        3 non-null      float64
 28  Boston Celtics_offReb     3 non-null      int64
 29  Boston Celtics_defReb     3 non-null      int64
 30  Boston Celtics_totReb     3 non-null      int64
 31  Boston Celtics_assists    3 non-null      int64
 32  Boston Celtics_pFouls     3 non-null      int64
 33  Boston Celtics_steals     3 non-null      int64
 34  Boston Celtics_turnovers  3 non-null      int64
 35  Boston Celtics_blocks     3 non-null      int64
 36  home_win                  3 non-null      int64
dtypes: float64(6), int64(31)
memory usage: 912.0 bytes

In [438]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

scaler = MinMaxScaler()

X = scaler.fit_transform(new_df.drop(columns=['home_win', f'{home_team}_points', f'{visitor_team}_points']))

X_df = pd.DataFrame(X, columns=new_df.drop(columns=['home_win', f'{home_team}_points', f'{visitor_team}_points']).columns)
y = new_df['home_win']

# Splitting into testing/train data
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

# Create decision tree regression instance
model = DecisionTreeClassifier()

# Fit model
model = model.fit(X_train, y_train)

# Making predictions using scaled data
predictions = model.predict(X_test)

# Print predicted price for tested features
predictions

array([1], dtype=int64)

In [439]:
# Create a new data instance with zeros for all one-hot columns
input_data = {col: 0 for col in X_df.columns}
input_data[f'home_team_{home_team}'] = 1
input_data[f'visitor_team_{visitor_team}'] = 1

# Convert to DataFrame
input_df = pd.DataFrame([input_data])
for col in X_df.columns:
    if col not in input_df.columns:
        input_df[col] = 0

input_df = input_df[X_df.columns]

# Apply the same MinMaxScaler used on X_df
input_scaled = scaler.transform(input_df)

# Predict total points
predicted_winner = model.predict(input_scaled)[0]

winning_team = home_team if  predicted_winner == 1 else visitor_team
print("Predicted Winner:", winning_team)

Predicted Winner: Boston Celtics

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [440]:
print("Accuracy:", accuracy_score(y_test, predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
print("Classification Report:\n", classification_report(y_test, predictions))

Accuracy: 0.0
Confusion Matrix:
 [[0 1]
 [0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0

c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))