In [375]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [376]:
game_statistics_df = pd.read_csv('./data/gameStatistics.csv')
game_statistics_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,NaN,NaN,NaN,NaN,NaN,NaN,88,29,77,37.7,...,30,46,20,20,10,10,5,20,240:00,New York Knicks
1,NaN,NaN,NaN,NaN,NaN,NaN,125,47,85,55.3,...,20,26,21,24,5,5,3,1,240:00,Dallas Mavericks
2,NaN,NaN,NaN,NaN,NaN,NaN,106,38,96,39.6,...,40,42,26,16,7,14,6,17,240:00,Brooklyn Nets
3,NaN,NaN,NaN,NaN,NaN,NaN,102,39,81,48.1,...,35,50,20,18,9,21,5,1,240:00,Cleveland Cavaliers
4,NaN,NaN,NaN,NaN,NaN,NaN,104,36,83,43.4,...,37,52,21,22,6,14,6,12,240:00,Detroit Pistons

In [377]:
game_statistics_df.describe()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus
count,0.0,0.0,0.0,0.0,0.0,0.0,2495.000000,2495.000000,2495.000000,2495.000000,...,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,114.954709,42.089780,88.414429,47.688377,...,35.576313,10.553106,32.583166,43.136273,25.664128,19.361122,7.524649,13.868136,4.909419,-2.282164
std,NaN,NaN,NaN,NaN,NaN,NaN,12.482287,5.343152,7.614180,5.508311,...,8.348361,3.879434,5.392103,6.680402,5.082422,4.308178,2.990913,4.006491,2.507849,14.934196
min,NaN,NaN,NaN,NaN,NaN,NaN,73.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-62.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,106.000000,38.000000,84.000000,43.900000,...,30.000000,8.000000,29.000000,39.000000,22.000000,17.000000,5.000000,11.000000,3.000000,-12.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,115.000000,42.000000,88.000000,47.500000,...,35.400000,10.000000,32.000000,43.000000,25.000000,19.000000,7.000000,14.000000,5.000000,-3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,123.000000,46.000000,93.000000,51.400000,...,41.000000,13.000000,36.000000,47.000000,29.000000,22.000000,9.000000,16.000000,6.000000,8.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,175.000000,65.000000,121.000000,66.300000,...,63.400000,28.000000,60.000000,73.000000,47.000000,35.000000,22.000000,33.000000,17.000000,56.000000

In [378]:
game_statistics_df.dtypes

visitor_fastBreakPoints       float64
visitor_pointsInPaint         float64
visitor_biggestLead           float64
visitor_secondChancePoints    float64
visitor_pointsOffTurnovers    float64
visitor_longestRun            float64
visitor_points                  int64
visitor_fgm                     int64
visitor_fga                     int64
visitor_fgp                   float64
visitor_ftm                     int64
visitor_fta                     int64
visitor_ftp                   float64
visitor_tpm                     int64
visitor_tpa                     int64
visitor_tpp                   float64
visitor_offReb                  int64
visitor_defReb                  int64
visitor_totReb                  int64
visitor_assists                 int64
visitor_pFouls                  int64
visitor_steals                  int64
visitor_turnovers               int64
visitor_blocks                  int64
visitor_plusMinus               int64
visitor_min                    object
game_id                         int64
visitor_team                   object
home_fastBreakPoints          float64
home_pointsInPaint            float64
home_biggestLead              float64
home_secondChancePoints       float64
home_pointsOffTurnovers       float64
home_longestRun               float64
home_points                     int64
home_fgm                        int64
home_fga                        int64
home_fgp                      float64
home_ftm                        int64
home_fta                        int64
home_ftp                      float64
home_tpm                        int64
home_tpa                        int64
home_tpp                      float64
home_offReb                     int64
home_defReb                     int64
home_totReb                     int64
home_assists                    int64
home_pFouls                     int64
home_steals                     int64
home_turnovers                  int64
home_blocks                     int64
home_plusMinus                  int64
home_min                       object
home_team                      object
dtype: object

In [379]:
# Convert values in percentage columns to decimal form
game_statistics_df[['visitor_ftp', 'visitor_fgp', 'visitor_tpp', 'home_ftp', 'home_fgp','home_tpp']] = game_statistics_df[
    ['visitor_ftp', 
     'visitor_fgp', 
     'visitor_tpp', 
     'home_ftp', 
     'home_fgp',
     'home_tpp']
    ].apply(lambda x: x / 100)

In [380]:
# Drop irrelevant columns
game_statistics_df = game_statistics_df.drop(columns=['visitor_fastBreakPoints', 'visitor_pointsInPaint',
       'visitor_biggestLead', 'visitor_secondChancePoints',
       'visitor_pointsOffTurnovers', 'visitor_longestRun','visitor_plusMinus',
       'visitor_min','home_fastBreakPoints',
       'home_pointsInPaint', 'home_biggestLead', 'home_secondChancePoints',
       'home_pointsOffTurnovers', 'home_longestRun','home_plusMinus', 'home_min','game_id'])

# Display
game_statistics_df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team
0,88,29,77,0.377,16,23,0.696,14,46,0.304,...,0.294,16,30,46,20,20,10,10,5,New York Knicks
1,125,47,85,0.553,23,32,0.719,8,19,0.421,...,0.412,6,20,26,21,24,5,5,3,Dallas Mavericks
2,106,38,96,0.396,19,21,0.905,11,41,0.268,...,0.382,2,40,42,26,16,7,14,6,Brooklyn Nets
3,102,39,81,0.481,17,24,0.708,7,21,0.333,...,0.342,15,35,50,20,18,9,21,5,Cleveland Cavaliers
4,104,36,83,0.434,22,26,0.846,10,34,0.294,...,0.370,15,37,52,21,22,6,14,6,Detroit Pistons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2490,108,39,91,0.429,20,31,0.645,10,37,0.270,...,0.350,8,42,50,29,22,6,11,4,Chicago Bulls
2491,103,35,77,0.455,23,30,0.767,10,29,0.345,...,0.476,9,32,41,23,19,5,13,7,Milwaukee Bucks
2492,111,42,98,0.429,18,20,0.900,9,38,0.237,...,0.405,7,37,44,31,20,12,12,9,Houston Rockets
2493,115,43,84,0.512,16,20,0.800,13,35,0.371,...,0.375,13,26,39,30,17,12,10,5,San Antonio Spurs
2494,127,51,99,0.515,8,10,0.800,17,42,0.405,...,0.235,7,35,42,25,11,7,12,6,Los Angeles Lakers

In [381]:
# Copy encoded data frame
target_dataframe = game_statistics_df.copy()

# Create first target column 'winner'
target_dataframe['winner'] = target_dataframe.apply(
    lambda row: 1 if row['home_points'] > row['visitor_points'] else 0,
    axis=1
)
# Create second target column 'total_points'
target_dataframe['total_points'] = target_dataframe['home_points'] + target_dataframe['visitor_points']

# Display
target_dataframe

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team,winner,total_points
0,88,29,77,0.377,16,23,0.696,14,46,0.304,...,30,46,20,20,10,10,5,New York Knicks,1,196
1,125,47,85,0.553,23,32,0.719,8,19,0.421,...,20,26,21,24,5,5,3,Dallas Mavericks,1,251
2,106,38,96,0.396,19,21,0.905,11,41,0.268,...,40,42,26,16,7,14,6,Brooklyn Nets,1,229
3,102,39,81,0.481,17,24,0.708,7,21,0.333,...,35,50,20,18,9,21,5,Cleveland Cavaliers,1,205
4,104,36,83,0.434,22,26,0.846,10,34,0.294,...,37,52,21,22,6,14,6,Detroit Pistons,1,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2490,108,39,91,0.429,20,31,0.645,10,37,0.270,...,42,50,29,22,6,11,4,Chicago Bulls,1,235
2491,103,35,77,0.455,23,30,0.767,10,29,0.345,...,32,41,23,19,5,13,7,Milwaukee Bucks,1,209
2492,111,42,98,0.429,18,20,0.900,9,38,0.237,...,37,44,31,20,12,12,9,Houston Rockets,1,228
2493,115,43,84,0.512,16,20,0.800,13,35,0.371,...,26,39,30,17,12,10,5,San Antonio Spurs,1,243
2494,127,51,99,0.515,8,10,0.800,17,42,0.405,...,35,42,25,11,7,12,6,Los Angeles Lakers,0,227

In [382]:
# Apply one-hot encoding and convert to booleans to ingeters
encoded_df = pd.get_dummies(target_dataframe, columns=['visitor_team', 'home_team'])

# Display
encoded_df = encoded_df.replace({True: 1, False: 0})
encoded_df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_9180\4203132407.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  encoded_df = encoded_df.replace({True: 1, False: 0})

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_team_Oklahoma City Thunder,home_team_Orlando Magic,home_team_Philadelphia 76ers,home_team_Phoenix Suns,home_team_Portland Trail Blazers,home_team_Sacramento Kings,home_team_San Antonio Spurs,home_team_Toronto Raptors,home_team_Utah Jazz,home_team_Washington Wizards
0,88,29,77,0.377,16,23,0.696,14,46,0.304,...,0,0,0,0,0,0,0,0,0,0
1,125,47,85,0.553,23,32,0.719,8,19,0.421,...,0,0,0,0,0,0,0,0,0,0
2,106,38,96,0.396,19,21,0.905,11,41,0.268,...,0,0,0,0,0,0,0,0,0,0
3,102,39,81,0.481,17,24,0.708,7,21,0.333,...,0,0,0,0,0,0,0,0,0,0
4,104,36,83,0.434,22,26,0.846,10,34,0.294,...,0,0,0,0,0,0,0,0,0,0

# Prepare Machine Learning Model

In [389]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

X = encoded_df.drop(columns=['winner','home_points', 'visitor_points', 'total_points'])
X_df = pd.DataFrame(X, columns=encoded_df.drop(columns=['winner','home_points', 'visitor_points', 'total_points']).columns)

# Create both target variables
y_winner = encoded_df['winner']
y_total_points = encoded_df['total_points']

# Splitting data
X_train, X_test, y_train_winner, y_test_winner = train_test_split(X_df, y_winner, test_size=0.2, random_state=42)
_, _, y_train_points, y_test_points = train_test_split(X_df, y_total_points, test_size=0.2, random_state=42)

# Scaling the training data
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Train the classification model (winner prediction)
clf_model = DecisionTreeClassifier().fit(X_train, y_train_winner)

# Train regression model (total_points)
linear_model = LinearRegression().fit(X_train_scaled, y_train_points)

# Scale the test data
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # type: ignore

# Evaluate the classification model
winner_predictions = clf_model.predict(X_test_scaled)  # Predictions for winner
print("Winner Prediction Evaluation:")
print("Accuracy:", accuracy_score(y_test_winner, winner_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test_winner, winner_predictions))
print("Classification Report:\n", classification_report(y_test_winner, winner_predictions))

Winner Prediction Evaluation:
Accuracy: 0.5511022044088176
Confusion Matrix:
 [[234  21]
 [203  41]]
Classification Report:
               precision    recall  f1-score   support

           0       0.54      0.92      0.68       255
           1       0.66      0.17      0.27       244

    accuracy                           0.55       499
   macro avg       0.60      0.54      0.47       499
weighted avg       0.60      0.55      0.48       499

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [391]:
visitor_team = input("Enter Away Team: ")
home_team = input("Enter Home Team: ")

# Create input data with correct features
input_data = {col: 0 for col in X_df.columns}
if f'home_team_{home_team}' in input_data:
    input_data[f'home_team_{home_team}'] = 1
if f'visitor_team_{visitor_team}' in input_data:
    input_data[f'visitor_team_{visitor_team}'] = 1

# Convert to DataFrame and scale
input_df = pd.DataFrame([input_data])
input_scaled = scaler.transform(input_df)

# Predict the winner and total points
predicted_winner = clf_model.predict(input_scaled)[0]
predicted_total_points = linear_model.predict(input_scaled)[0]

# Map winner prediction to the team name
winning_team = home_team if predicted_winner == 1 else visitor_team

# Print results
print("Predicted Winner:", winning_team)
print("Predicted Total Points:", round(predicted_total_points, 0))

Predicted Winner: San Antonio Spurs
Predicted Total Points: 208.0

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(