In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [29]:
game_statistics_df = pd.read_csv('./data/gameStatistics.csv') # change path to ./data/gameStatistics
game_statistics_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,NaN,NaN,NaN,NaN,NaN,NaN,88,29,77,37.7,...,30,46,20,20,10,10,5,20,240:00,New York Knicks
1,NaN,NaN,NaN,NaN,NaN,NaN,125,47,85,55.3,...,20,26,21,24,5,5,3,1,240:00,Dallas Mavericks
2,NaN,NaN,NaN,NaN,NaN,NaN,106,38,96,39.6,...,40,42,26,16,7,14,6,17,240:00,Brooklyn Nets
3,NaN,NaN,NaN,NaN,NaN,NaN,102,39,81,48.1,...,35,50,20,18,9,21,5,1,240:00,Cleveland Cavaliers
4,NaN,NaN,NaN,NaN,NaN,NaN,104,36,83,43.4,...,37,52,21,22,6,14,6,12,240:00,Detroit Pistons

In [30]:
game_statistics_df.describe()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus
count,0.0,0.0,0.0,0.0,0.0,0.0,2495.000000,2495.000000,2495.000000,2495.000000,...,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,114.954709,42.089780,88.414429,47.688377,...,35.576313,10.553106,32.583166,43.136273,25.664128,19.361122,7.524649,13.868136,4.909419,-2.282164
std,NaN,NaN,NaN,NaN,NaN,NaN,12.482287,5.343152,7.614180,5.508311,...,8.348361,3.879434,5.392103,6.680402,5.082422,4.308178,2.990913,4.006491,2.507849,14.934196
min,NaN,NaN,NaN,NaN,NaN,NaN,73.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-62.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,106.000000,38.000000,84.000000,43.900000,...,30.000000,8.000000,29.000000,39.000000,22.000000,17.000000,5.000000,11.000000,3.000000,-12.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,115.000000,42.000000,88.000000,47.500000,...,35.400000,10.000000,32.000000,43.000000,25.000000,19.000000,7.000000,14.000000,5.000000,-3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,123.000000,46.000000,93.000000,51.400000,...,41.000000,13.000000,36.000000,47.000000,29.000000,22.000000,9.000000,16.000000,6.000000,8.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,175.000000,65.000000,121.000000,66.300000,...,63.400000,28.000000,60.000000,73.000000,47.000000,35.000000,22.000000,33.000000,17.000000,56.000000

In [31]:
game_statistics_df.dtypes

visitor_fastBreakPoints       float64
visitor_pointsInPaint         float64
visitor_biggestLead           float64
visitor_secondChancePoints    float64
visitor_pointsOffTurnovers    float64
visitor_longestRun            float64
visitor_points                  int64
visitor_fgm                     int64
visitor_fga                     int64
visitor_fgp                   float64
visitor_ftm                     int64
visitor_fta                     int64
visitor_ftp                   float64
visitor_tpm                     int64
visitor_tpa                     int64
visitor_tpp                   float64
visitor_offReb                  int64
visitor_defReb                  int64
visitor_totReb                  int64
visitor_assists                 int64
visitor_pFouls                  int64
visitor_steals                  int64
visitor_turnovers               int64
visitor_blocks                  int64
visitor_plusMinus               int64
visitor_min                    object
game_id                         int64
visitor_team                   object
home_fastBreakPoints          float64
home_pointsInPaint            float64
home_biggestLead              float64
home_secondChancePoints       float64
home_pointsOffTurnovers       float64
home_longestRun               float64
home_points                     int64
home_fgm                        int64
home_fga                        int64
home_fgp                      float64
home_ftm                        int64
home_fta                        int64
home_ftp                      float64
home_tpm                        int64
home_tpa                        int64
home_tpp                      float64
home_offReb                     int64
home_defReb                     int64
home_totReb                     int64
home_assists                    int64
home_pFouls                     int64
home_steals                     int64
home_turnovers                  int64
home_blocks                     int64
home_plusMinus                  int64
home_min                       object
home_team                      object
dtype: object

In [32]:
# Convert values in percentage columns to decimal form
game_statistics_df[['visitor_ftp', 'visitor_fgp', 'visitor_tpp', 'home_ftp', 'home_fgp','home_tpp']] = game_statistics_df[
    ['visitor_ftp', 
     'visitor_fgp', 
     'visitor_tpp', 
     'home_ftp', 
     'home_fgp',
     'home_tpp']
    ].apply(lambda x: x / 100)

In [33]:
# Drop irrelevant columns
game_statistics_df = game_statistics_df.drop(columns=['visitor_fastBreakPoints', 'visitor_pointsInPaint',
       'visitor_biggestLead', 'visitor_secondChancePoints',
       'visitor_pointsOffTurnovers', 'visitor_longestRun','visitor_plusMinus',
       'visitor_min','home_fastBreakPoints',
       'home_pointsInPaint', 'home_biggestLead', 'home_secondChancePoints',
       'home_pointsOffTurnovers', 'home_longestRun','home_plusMinus', 'home_min',])

# Display
game_statistics_df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team
0,88,29,77,0.377,16,23,0.696,14,46,0.304,...,0.294,16,30,46,20,20,10,10,5,New York Knicks
1,125,47,85,0.553,23,32,0.719,8,19,0.421,...,0.412,6,20,26,21,24,5,5,3,Dallas Mavericks
2,106,38,96,0.396,19,21,0.905,11,41,0.268,...,0.382,2,40,42,26,16,7,14,6,Brooklyn Nets
3,102,39,81,0.481,17,24,0.708,7,21,0.333,...,0.342,15,35,50,20,18,9,21,5,Cleveland Cavaliers
4,104,36,83,0.434,22,26,0.846,10,34,0.294,...,0.370,15,37,52,21,22,6,14,6,Detroit Pistons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2490,108,39,91,0.429,20,31,0.645,10,37,0.270,...,0.350,8,42,50,29,22,6,11,4,Chicago Bulls
2491,103,35,77,0.455,23,30,0.767,10,29,0.345,...,0.476,9,32,41,23,19,5,13,7,Milwaukee Bucks
2492,111,42,98,0.429,18,20,0.900,9,38,0.237,...,0.405,7,37,44,31,20,12,12,9,Houston Rockets
2493,115,43,84,0.512,16,20,0.800,13,35,0.371,...,0.375,13,26,39,30,17,12,10,5,San Antonio Spurs
2494,127,51,99,0.515,8,10,0.800,17,42,0.405,...,0.235,7,35,42,25,11,7,12,6,Los Angeles Lakers

In [34]:
# Export this dataframe to the version3_mlFlies folder
# This dataframe and the one used in version1 will be combined for more features
# Export as csv file
game_statistics_df.to_csv('./version3_mlFiles/gameStatisticsFinalDataFrame.csv', index=False)

# Filter Data Frame for Chosen Teams

In [35]:
# Define the home and visitor teams
home_team = input("Enter Home Team: ")  # Replace with desired home team
visitor_team = input("Enter Away Team: ")  # Replace with desired visitor team

# Filter data frame based on previous condition
filtered_df = game_statistics_df[(game_statistics_df['home_team'] == home_team) & (game_statistics_df['visitor_team'] == visitor_team)]

# Drop home and visitor columns
filtered_df = filtered_df.drop(columns=['home_team', 'visitor_team'])

# Update column names to match visitor and home team stats
updated_cols = []
for col in filtered_df.columns:
    if f"visitor_" in col:
        updated_cols.append(col.replace('visitor', visitor_team))
    elif f"home_" in col:
        updated_cols.append(col.replace('home', home_team))
    else:
        updated_cols.append(col)

filtered_df.columns = updated_cols

# Display
filtered_df

,LA Clippers_points,LA Clippers_fgm,LA Clippers_fga,LA Clippers_fgp,LA Clippers_ftm,LA Clippers_fta,LA Clippers_ftp,LA Clippers_tpm,LA Clippers_tpa,LA Clippers_tpp,...,Minnesota Timberwolves_tpa,Minnesota Timberwolves_tpp,Minnesota Timberwolves_offReb,Minnesota Timberwolves_defReb,Minnesota Timberwolves_totReb,Minnesota Timberwolves_assists,Minnesota Timberwolves_pFouls,Minnesota Timberwolves_steals,Minnesota Timberwolves_turnovers,Minnesota Timberwolves_blocks
391,101,35,83,0.422,20,23,0.870,11,28,0.393,...,26,0.346,10,36,46,22,20,14,19,8
1643,100,34,84,0.405,23,26,0.885,9,28,0.321,...,34,0.324,8,32,40,33,20,9,13,7
1819,100,34,72,0.472,21,25,0.840,11,30,0.367,...,33,0.364,19,29,48,26,20,11,11,6

# Prepare Machine Learning Model

In [36]:
# Create a column to check if the home team won
stats_df = filtered_df.copy()
stats_df['winner'] = stats_df.apply(
    lambda row: 1 if row[f'{home_team}_points'] > row[f'{visitor_team}_points'] else 0,
    axis=1
)
stats_df

,LA Clippers_points,LA Clippers_fgm,LA Clippers_fga,LA Clippers_fgp,LA Clippers_ftm,LA Clippers_fta,LA Clippers_ftp,LA Clippers_tpm,LA Clippers_tpa,LA Clippers_tpp,...,Minnesota Timberwolves_tpp,Minnesota Timberwolves_offReb,Minnesota Timberwolves_defReb,Minnesota Timberwolves_totReb,Minnesota Timberwolves_assists,Minnesota Timberwolves_pFouls,Minnesota Timberwolves_steals,Minnesota Timberwolves_turnovers,Minnesota Timberwolves_blocks,winner
391,101,35,83,0.422,20,23,0.870,11,28,0.393,...,0.346,10,36,46,22,20,14,19,8,1
1643,100,34,84,0.405,23,26,0.885,9,28,0.321,...,0.324,8,32,40,33,20,9,13,7,1
1819,100,34,72,0.472,21,25,0.840,11,30,0.367,...,0.364,19,29,48,26,20,11,11,6,1

In [37]:
# Set target column
target_column = 'winner'

# Look for correlation between columns and 'home_win' column
correlations = stats_df.corr(numeric_only=True)[target_column].sort_values(ascending=False)
correlations

LA Clippers_points                 NaN
LA Clippers_fgm                    NaN
LA Clippers_fga                    NaN
LA Clippers_fgp                    NaN
LA Clippers_ftm                    NaN
LA Clippers_fta                    NaN
LA Clippers_ftp                    NaN
LA Clippers_tpm                    NaN
LA Clippers_tpa                    NaN
LA Clippers_tpp                    NaN
LA Clippers_offReb                 NaN
LA Clippers_defReb                 NaN
LA Clippers_totReb                 NaN
LA Clippers_assists                NaN
LA Clippers_pFouls                 NaN
LA Clippers_steals                 NaN
LA Clippers_turnovers              NaN
LA Clippers_blocks                 NaN
game_id                            NaN
Minnesota Timberwolves_points      NaN
Minnesota Timberwolves_fgm         NaN
Minnesota Timberwolves_fga         NaN
Minnesota Timberwolves_fgp         NaN
Minnesota Timberwolves_ftm         NaN
Minnesota Timberwolves_fta         NaN
Minnesota Timberwolves_ftp         NaN
Minnesota Timberwolves_tpm         NaN
Minnesota Timberwolves_tpa         NaN
Minnesota Timberwolves_tpp         NaN
Minnesota Timberwolves_offReb      NaN
Minnesota Timberwolves_defReb      NaN
Minnesota Timberwolves_totReb      NaN
Minnesota Timberwolves_assists     NaN
Minnesota Timberwolves_pFouls      NaN
Minnesota Timberwolves_steals      NaN
Minnesota Timberwolves_turnovers   NaN
Minnesota Timberwolves_blocks      NaN
winner                             NaN
Name: winner, dtype: float64

In [38]:
# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column]

# Set conditions to find feature columns
feature_columns = correlations[correlations > -1]

# Create new data frame with chosen feature columns
new_df = stats_df[feature_columns.index]
new_df

Empty DataFrame
Columns: []
Index: [391, 1643, 1819]

In [39]:
new_df.isnull().sum()

Series([], dtype: float64)

In [40]:
new_df.columns

Index([], dtype='object')

In [41]:
new_df = new_df.dropna()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 391 to 1819
Empty DataFrame

In [42]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

scaler = MinMaxScaler()

X = scaler.fit_transform(new_df.drop(columns=['winner', f'{home_team}_points', f'{visitor_team}_points']))

X_df = pd.DataFrame(X, columns=new_df.drop(columns=['winner', f'{home_team}_points', f'{visitor_team}_points']).columns)
y = new_df['winner']

# Splitting into testing/train data
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

# Create decision tree regression instance
model = DecisionTreeClassifier()

# Fit model
model = model.fit(X_train, y_train)

# Making predictions using scaled data
predictions = model.predict(X_test)

# Print predicted price for tested features
predictions

KeyError: "['winner', 'Minnesota Timberwolves_points', 'LA Clippers_points'] not found in axis"

In [ ]:
# Create a new data instance with zeros for all one-hot columns
input_data = {col: 0 for col in X_df.columns}
input_data[f'home_team_{home_team}'] = 1
input_data[f'visitor_team_{visitor_team}'] = 1

# Convert to DataFrame
input_df = pd.DataFrame([input_data])
for col in X_df.columns:
    if col not in input_df.columns:
        input_df[col] = 0

input_df = input_df[X_df.columns]

# Apply the same MinMaxScaler used on X_df
input_scaled = scaler.transform(input_df)

# Predict total points
predicted_winner = model.predict(input_scaled)[0]

winning_team = home_team if  predicted_winner == 1 else visitor_team
print("Predicted Winner:", winning_team)

Predicted Winner: Boston Celtics

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
print("Accuracy:", accuracy_score(y_test, predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
print("Classification Report:\n", classification_report(y_test, predictions))

Accuracy: 0.5
Confusion Matrix:
 [[0 1]
 [0 1]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))