In [166]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [167]:
game_df = pd.read_csv('./data/gameStatistics.csv') # change path to ./data/gameStatistics contains the game_ids when cleaned properly
game_df.head()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus,home_min,home_team
0,NaN,NaN,NaN,NaN,NaN,NaN,120,46,87,52.9,...,26,38,21,16,7,9,8,-2,240:00,Boston Celtics
1,NaN,NaN,NaN,NaN,NaN,NaN,123,51,104,49.0,...,34,43,28,15,7,12,6,-1,240:00,Boston Celtics
2,NaN,NaN,NaN,NaN,NaN,NaN,93,37,89,41.6,...,39,50,27,14,15,13,7,30,240:00,Boston Celtics
3,NaN,NaN,NaN,NaN,NaN,NaN,125,49,93,52.7,...,36,49,24,13,8,9,2,-8,240:00,Atlanta Hawks
4,NaN,NaN,NaN,NaN,NaN,NaN,116,38,75,50.7,...,25,45,35,17,16,16,2,1,240:00,Atlanta Hawks

In [168]:
game_df.describe()

,visitor_fastBreakPoints,visitor_pointsInPaint,visitor_biggestLead,visitor_secondChancePoints,visitor_pointsOffTurnovers,visitor_longestRun,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_plusMinus
count,0.0,0.0,0.0,0.0,0.0,0.0,299.000000,299.000000,299.000000,299.000000,...,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,114.133779,41.876254,88.471572,47.414716,...,35.436120,10.468227,32.806020,43.274247,25.735786,18.060201,7.123746,13.705686,4.725753,-3.197324
std,NaN,NaN,NaN,NaN,NaN,NaN,13.687628,5.682429,8.393132,5.356040,...,8.172665,3.906821,5.609421,6.955156,5.237362,4.386112,3.003589,4.210127,2.442295,16.302237
min,NaN,NaN,NaN,NaN,NaN,NaN,77.000000,21.000000,43.000000,34.300000,...,10.300000,2.000000,16.000000,21.000000,9.000000,8.000000,0.000000,3.000000,0.000000,-52.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,105.000000,38.000000,84.000000,43.450000,...,29.650000,7.000000,29.000000,38.000000,22.000000,15.000000,5.000000,11.000000,3.000000,-13.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,113.000000,41.000000,89.000000,47.300000,...,35.000000,10.000000,32.000000,43.000000,25.000000,18.000000,7.000000,14.000000,4.000000,-3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,123.000000,45.000000,93.000000,51.100000,...,40.500000,13.000000,37.000000,48.000000,29.000000,21.000000,9.000000,16.000000,6.000000,8.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,157.000000,65.000000,115.000000,65.000000,...,61.100000,22.000000,48.000000,65.000000,41.000000,32.000000,16.000000,33.000000,13.000000,35.000000

In [169]:
game_df.dtypes

visitor_fastBreakPoints       float64
visitor_pointsInPaint         float64
visitor_biggestLead           float64
visitor_secondChancePoints    float64
visitor_pointsOffTurnovers    float64
visitor_longestRun            float64
visitor_points                  int64
visitor_fgm                     int64
visitor_fga                     int64
visitor_fgp                   float64
visitor_ftm                     int64
visitor_fta                     int64
visitor_ftp                   float64
visitor_tpm                     int64
visitor_tpa                     int64
visitor_tpp                   float64
visitor_offReb                  int64
visitor_defReb                  int64
visitor_totReb                  int64
visitor_assists                 int64
visitor_pFouls                  int64
visitor_steals                  int64
visitor_turnovers               int64
visitor_blocks                  int64
visitor_plusMinus               int64
visitor_min                    object
game_id                         int64
visitor_team                   object
home_fastBreakPoints          float64
home_pointsInPaint            float64
home_biggestLead              float64
home_secondChancePoints       float64
home_pointsOffTurnovers       float64
home_longestRun               float64
home_points                     int64
home_fgm                        int64
home_fga                        int64
home_fgp                      float64
home_ftm                        int64
home_fta                        int64
home_ftp                      float64
home_tpm                        int64
home_tpa                        int64
home_tpp                      float64
home_offReb                     int64
home_defReb                     int64
home_totReb                     int64
home_assists                    int64
home_pFouls                     int64
home_steals                     int64
home_turnovers                  int64
home_blocks                     int64
home_plusMinus                  int64
home_min                       object
home_team                      object
dtype: object

In [170]:
# Convert values in percentage columns to decimal form
game_df[['visitor_ftp', 'visitor_fgp', 'visitor_tpp', 'home_ftp', 'home_fgp','home_tpp']] = game_df[
    ['visitor_ftp', 
     'visitor_fgp', 
     'visitor_tpp', 
     'home_ftp', 
     'home_fgp',
     'home_tpp']
    ].apply(lambda x: x / 100)

In [171]:
# Drop irrelevant columns
game_df = game_df.drop(columns=['game_id','visitor_fastBreakPoints', 'visitor_pointsInPaint',
       'visitor_biggestLead', 'visitor_secondChancePoints',
       'visitor_pointsOffTurnovers', 'visitor_longestRun','visitor_plusMinus',
       'visitor_min','home_fastBreakPoints',
       'home_pointsInPaint', 'home_biggestLead', 'home_secondChancePoints',
       'home_pointsOffTurnovers', 'home_longestRun','home_plusMinus', 'home_min',])

# Display
game_df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,0.289,12,26,38,21,16,7,9,8,Boston Celtics
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,0.389,9,34,43,28,15,7,12,6,Boston Celtics
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,0.327,11,39,50,27,14,15,13,7,Boston Celtics
3,125,49,93,0.527,10,11,0.909,17,49,0.347,...,0.317,13,36,49,24,13,8,9,2,Atlanta Hawks
4,116,38,75,0.507,22,27,0.815,18,45,0.400,...,0.313,20,25,45,35,17,16,16,2,Atlanta Hawks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,112,42,108,0.389,18,21,0.857,10,48,0.208,...,0.200,12,47,59,24,18,8,13,9,Chicago Bulls
295,144,51,93,0.548,21,24,0.875,21,43,0.488,...,0.476,3,33,36,32,20,7,17,4,Chicago Bulls
296,119,45,93,0.484,17,21,0.810,12,38,0.316,...,0.286,14,37,51,25,17,8,23,2,Chicago Bulls
297,92,35,89,0.393,15,22,0.682,7,34,0.206,...,0.317,10,39,49,33,17,10,6,6,Dallas Mavericks
298,105,38,77,0.494,15,23,0.652,14,35,0.400,...,0.389,11,31,42,28,15,14,9,5,Chicago Bulls

In [172]:
# # Based on the column data and the fact that the home_team has the same missing data as the visitor_team
# # A function should be created to fill all the Null values with the average of those columns
# # Later will see if this affects how well the machine learning model works

# def fillNullCols(df):
#     # Find all data type 'int' or 'float' columns that have Null values
#     df.select_dtypes(include=['int', 'float'])

#     # Looks at the total percentage of null values in each columns
#     null_percentage = (df.isnull().sum() / len(df)) * 100

#     # Rule of thumb: Moderate Null Percentage (10-30%)
#     # Filling the null values with an appropriate value (like the mean, median, or mode) is often better in this range, especially if the column is critical for analysis

#     # Get columns from null_percentage with at least 20% with null values
#     null_columns = null_percentage[null_percentage >= 0.35].index

#     # Fill rows with the mode of the column
#     for column in null_columns:
#         mode_fill_value = df[column].mode()[0]
#         df[column] = df[column].fillna(mode_fill_value)

#     return df

# # Create new data frame
# stats_df = fillNullCols(game_df)
# stats_df.head()

In [173]:
# Create a column to check if the home team won
stats_df = game_df.copy()
stats_df['game_winner'] = stats_df.apply(
    lambda row: 1 if row['home_points'] > row['visitor_points'] else 0,
    axis=1
)
stats_df.head()

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,home_team,game_winner
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,12,26,38,21,16,7,9,8,Boston Celtics,0
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,9,34,43,28,15,7,12,6,Boston Celtics,0
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,11,39,50,27,14,15,13,7,Boston Celtics,1
3,125,49,93,0.527,10,11,0.909,17,49,0.347,...,13,36,49,24,13,8,9,2,Atlanta Hawks,0
4,116,38,75,0.507,22,27,0.815,18,45,0.400,...,20,25,45,35,17,16,16,2,Atlanta Hawks,1

In [174]:
# Set target column
target_column = 'game_winner'

# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column].sort_values(ascending=False)
correlations

game_winner          1.000000
home_points          0.400295
home_defReb          0.338273
home_tpp             0.331162
home_fgm             0.327760
home_tpm             0.284953
home_blocks          0.278438
home_assists         0.238584
home_totReb          0.209214
home_ftp             0.099413
home_ftm             0.082660
home_tpa             0.063943
home_fta             0.049952
home_steals          0.033179
visitor_pFouls       0.011635
visitor_turnovers   -0.017339
visitor_fga         -0.034412
visitor_offReb      -0.034423
home_offReb         -0.113237
home_turnovers      -0.146176
visitor_tpa         -0.147783
visitor_ftp         -0.149109
home_fgp            -0.149109
home_fga            -0.151383
visitor_fta         -0.158980
home_pFouls         -0.160402
visitor_steals      -0.199745
visitor_ftm         -0.210644
visitor_assists     -0.299546
visitor_blocks      -0.302387
visitor_tpm         -0.334544
visitor_tpp         -0.339888
visitor_totReb      -0.356206
visitor_defReb      -0.408431
visitor_fgm         -0.426788
visitor_fgp         -0.486527
visitor_points      -0.555202
Name: game_winner, dtype: float64

In [175]:
# Look for correlation between columns and 'total_points' column
correlations = stats_df.corr(numeric_only=True)[target_column]

# Set conditions to find feature columns
feature_columns = correlations[correlations > -1]

# Create new data frame with chosen feature columns
new_df = stats_df[feature_columns.index]

# Add 'visitor_team' and 'home_team' to the new DataFrame
new_df = pd.concat([stats_df[['home_team', 'visitor_team']], new_df], axis=1)
new_df

,home_team,visitor_team,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,...,home_tpp,home_offReb,home_defReb,home_totReb,home_assists,home_pFouls,home_steals,home_turnovers,home_blocks,game_winner
0,Boston Celtics,Atlanta Hawks,120,46,87,0.529,10,17,0.588,18,...,0.289,12,26,38,21,16,7,9,8,0
1,Boston Celtics,Atlanta Hawks,123,51,104,0.490,6,10,0.600,15,...,0.389,9,34,43,28,15,7,12,6,0
2,Boston Celtics,Atlanta Hawks,93,37,89,0.416,13,16,0.813,6,...,0.327,11,39,50,27,14,15,13,7,1
3,Atlanta Hawks,Boston Celtics,125,49,93,0.527,10,11,0.909,17,...,0.317,13,36,49,24,13,8,9,2,0
4,Atlanta Hawks,Boston Celtics,116,38,75,0.507,22,27,0.815,18,...,0.313,20,25,45,35,17,16,16,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,Chicago Bulls,Cleveland Cavaliers,112,42,108,0.389,18,21,0.857,10,...,0.200,12,47,59,24,18,8,13,9,1
295,Chicago Bulls,Cleveland Cavaliers,144,51,93,0.548,21,24,0.875,21,...,0.476,3,33,36,32,20,7,17,4,0
296,Chicago Bulls,Dallas Mavericks,119,45,93,0.484,17,21,0.810,12,...,0.286,14,37,51,25,17,8,23,2,0
297,Dallas Mavericks,Chicago Bulls,92,35,89,0.393,15,22,0.682,7,...,0.317,10,39,49,33,17,10,6,6,1
298,Chicago Bulls,Detroit Pistons,105,38,77,0.494,15,23,0.652,14,...,0.389,11,31,42,28,15,14,9,5,1

In [176]:
new_df = stats_df.copy()
new_df.isnull().sum()

visitor_points       0
visitor_fgm          0
visitor_fga          0
visitor_fgp          0
visitor_ftm          0
visitor_fta          0
visitor_ftp          0
visitor_tpm          0
visitor_tpa          0
visitor_tpp          0
visitor_offReb       0
visitor_defReb       0
visitor_totReb       0
visitor_assists      0
visitor_pFouls       0
visitor_steals       0
visitor_turnovers    0
visitor_blocks       0
visitor_team         0
home_points          0
home_fgm             0
home_fga             0
home_fgp             0
home_ftm             0
home_fta             0
home_ftp             0
home_tpm             0
home_tpa             0
home_tpp             0
home_offReb          0
home_defReb          0
home_totReb          0
home_assists         0
home_pFouls          0
home_steals          0
home_turnovers       0
home_blocks          0
home_team            0
game_winner          0
dtype: int64

In [177]:
new_df = new_df.dropna()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   visitor_points     299 non-null    int64
 1   visitor_fgm        299 non-null    int64
 2   visitor_fga        299 non-null    int64
 3   visitor_fgp        299 non-null    float64
 4   visitor_ftm        299 non-null    int64
 5   visitor_fta        299 non-null    int64
 6   visitor_ftp        299 non-null    float64
 7   visitor_tpm        299 non-null    int64
 8   visitor_tpa        299 non-null    int64
 9   visitor_tpp        299 non-null    float64
 10  visitor_offReb     299 non-null    int64
 11  visitor_defReb     299 non-null    int64
 12  visitor_totReb     299 non-null    int64
 13  visitor_assists    299 non-null    int64
 14  visitor_pFouls     299 non-null    int64
 15  visitor_steals     299 non-null    int64
 16  visitor_turnovers  299 non-null    int64
 17  visitor_blocks     299 non-null    int64
 18  visitor_team       299 non-null    object
 19  home_points        299 non-null    int64
 20  home_fgm           299 non-null    int64
 21  home_fga           299 non-null    int64
 22  home_fgp           299 non-null    float64
 23  home_ftm           299 non-null    int64
 24  home_fta           299 non-null    int64
 25  home_ftp           299 non-null    float64
 26  home_tpm           299 non-null    int64
 27  home_tpa           299 non-null    int64
 28  home_tpp           299 non-null    float64
 29  home_offReb        299 non-null    int64
 30  home_defReb        299 non-null    int64
 31  home_totReb        299 non-null    int64
 32  home_assists       299 non-null    int64
 33  home_pFouls        299 non-null    int64
 34  home_steals        299 non-null    int64
 35  home_turnovers     299 non-null    int64
 36  home_blocks        299 non-null    int64
 37  home_team          299 non-null    object
 38  game_winner        299 non-null    int64
dtypes: float64(6), int64(31), object(2)
memory usage: 91.2+ KB

In [178]:
# Apply one-hot encoding and convert to booleans to integers
encoded_df = pd.get_dummies(new_df, columns=['visitor_team', 'home_team'])

# Convert only the binary columns to integers
encoded_df = encoded_df.apply(lambda x: x.astype(int) if x.dtype == 'bool' else x)

# Display
encoded_df

,visitor_points,visitor_fgm,visitor_fga,visitor_fgp,visitor_ftm,visitor_fta,visitor_ftp,visitor_tpm,visitor_tpa,visitor_tpp,...,home_team_Oklahoma City Thunder,home_team_Orlando Magic,home_team_Philadelphia 76ers,home_team_Phoenix Suns,home_team_Portland Trail Blazers,home_team_Sacramento Kings,home_team_San Antonio Spurs,home_team_Toronto Raptors,home_team_Utah Jazz,home_team_Washington Wizards
0,120,46,87,0.529,10,17,0.588,18,36,0.500,...,0,0,0,0,0,0,0,0,0,0
1,123,51,104,0.490,6,10,0.600,15,44,0.341,...,0,0,0,0,0,0,0,0,0,0
2,93,37,89,0.416,13,16,0.813,6,31,0.194,...,0,0,0,0,0,0,0,0,0,0
3,125,49,93,0.527,10,11,0.909,17,49,0.347,...,0,0,0,0,0,0,0,0,0,0
4,116,38,75,0.507,22,27,0.815,18,45,0.400,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,112,42,108,0.389,18,21,0.857,10,48,0.208,...,0,0,0,0,0,0,0,0,0,0
295,144,51,93,0.548,21,24,0.875,21,43,0.488,...,0,0,0,0,0,0,0,0,0,0
296,119,45,93,0.484,17,21,0.810,12,38,0.316,...,0,0,0,0,0,0,0,0,0,0
297,92,35,89,0.393,15,22,0.682,7,34,0.206,...,0,0,0,0,0,0,0,0,0,0
298,105,38,77,0.494,15,23,0.652,14,35,0.400,...,0,0,0,0,0,0,0,0,0,0

In [179]:
# # Define the home and visitor teams
# home_team = input("Enter Away Team: ")  # Replace with desired home team
# visitor_team = input("Enter Home Team: ")  # Replace with desired visitor team

# # Create a new data instance with zeros for all one-hot columns
# input_data = {col: 0 for col in encoded_df.columns}
# input_data[f'home_team_{home_team}'] = 1
# input_data[f'visitor_team_{visitor_team}'] = 1

# # Convert to DataFrame
# input_df = pd.DataFrame([input_data])

In [180]:
# input_df[[f"home_team_{home_team}", f"visitor_team_{visitor_team}", "home_points"]]

In [182]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

scaler = MinMaxScaler()

X = scaler.fit_transform(encoded_df.drop(columns=['game_winner', 'home_points', 'visitor_points']))

X_df = pd.DataFrame(X, columns=encoded_df.drop(columns=['game_winner', 'home_points', 'visitor_points']).columns)
y = encoded_df['game_winner']

# Splitting into testing/train data
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

# Create decision tree regression instance
model = DecisionTreeClassifier()

# Fit model
model = model.fit(X_train, y_train)

# Making predictions using scaled data
predictions = model.predict(X_test)

# Print predicted price for tested features
predictions

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [183]:
# Define the home and visitor teams
home_team = input("Enter Away Team: ")  # Replace with desired home team
visitor_team = input("Enter Home Team: ")  # Replace with desired visitor team

# Create a new data instance with zeros for all one-hot columns
input_data = {col: 0 for col in X_df.columns}
input_data[f'home_team_{home_team}'] = 1
input_data[f'visitor_team_{visitor_team}'] = 1

# # Convert to DataFrame
input_df = pd.DataFrame([input_data])
for col in X_df.columns:
    if col not in input_df.columns:
        input_df[col] = 0

input_df = input_df[X_df.columns]

# Apply the same MinMaxScaler used on X_df
input_scaled = scaler.transform(input_df)

# Predict total points
predicted_winner = model.predict(input_scaled)[0]

winning_team = home_team if  predicted_winner == 1 else visitor_team
print("Predicted Winner:", winning_team)

Predicted Winner: Orlando Magic

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [184]:
print("Accuracy:", accuracy_score(y_test, predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
print("Classification Report:\n", classification_report(y_test, predictions))

Accuracy: 0.7166666666666667
Confusion Matrix:
 [[23 10]
 [ 7 20]]
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.70      0.73        33
           1       0.67      0.74      0.70        27

    accuracy                           0.72        60
   macro avg       0.72      0.72      0.72        60
weighted avg       0.72      0.72      0.72        60